facturacio/urls.py
from django.conf.urls import patterns, url
from .views import EmpresesPendingRevisionListView


urlpatterns = patterns(

    'facturacio.views',

    url(r'^llistat_empreses_pao/(?P<kind>client|proveidor)/$', 'llistat_empreses_pao',       name="llistat_empreses_pao"),
    
    url(r'^llistat_quotes_trimestrals/$',                    'llistat_quotes_trimestrals',   name='llistat_quotes_trimestrals'),

    url(r'^validar_empresa/(?P<empresa_id>\d+)/$',           'validar_empresa',              name='validar_empresa'),
    url(r'^rebutjar_empresa/(?P<empresa_id>\d+)/$',           'rebutjar_empresa',              name='rebutjar_empresa'),
    url(r'^modificar_empresa/(?P<empresa_id>\d+)/$',    'modificar_empresa', name='modificar_empresa'),
    url(r'^validacio_empreses/$',               EmpresesPendingRevisionListView.as_view(),   name='validacio_empreses'),

    url(r'^buscar_empresa/(?P<kind>\w+)/(?P<nif>\w+)$',      'buscar_empresa',               name="buscar_empresa"),
    url(r'^buscar_empresa/(?P<kind>\w+)$',                   'buscar_empresa',               name="buscar_empresa"),


    url(r'^crear_factura_emesa/$',                           'crear_factura_emesa',          name='crear_factura_emesa'),
    url(r'^crear_factura_emesa/(?P<id_client>\d+)$',         'crear_factura_emesa',          name='crear_factura_emesa'),
    url(r'^linies_factura_emesa/(?P<id_factura>\d+)$',       'editar_linies_factura_emesa',  name='editar_linies_factura_emesa'),
    url(r'^confirmar_factura_emesa/(?P<id_factura>\d+)$',    'confirmar_factura_emesa',      name='confirmar_factura_emesa'),
    url(r'^veure_factura_emesa/(?P<id_factura>\d+)$',        'veure_factura_emesa',          name='veure_factura_emesa'),
    url(r'^rectificar_factura_emesa/(?P<id_factura>\d+)$',    'rectificar_factura_emesa',      name='rectificar_factura_emesa'),

    url(r'^crear_factura_rebuda/$',                          'crear_factura_rebuda',         name='crear_factura_rebuda'),
    url(r'^crear_factura_rebuda/(?P<id_proveidor>\d+)$',     'crear_factura_rebuda',         name='crear_factura_rebuda'),
    url(r'^linies_factura_rebuda/(?P<id_factura>\d+)$',      'editar_linies_factura_rebuda', name='editar_linies_factura_rebuda'),
    url(r'^veure_factura_rebuda/(?P<id_factura>\d+)$',       'veure_factura_rebuda',         name='veure_factura_rebuda'),
    url(r'^rectificar_factura_rebuda/(?P<id_factura>\d+)$',    'rectificar_factura_rebuda',      name='rectificar_factura_rebuda'),
    url(r'^validacio_factures_rebudes/$',                    'validacio_factures_rebudes',   name='validacio_factures_rebudes'),

    url(r'^resum_facturacio_projecte/$',                     'resum_facturacio_projecte',    name='resum_facturacio_projecte'),
    url(r'^resum_facturacio_projecte/(?P<id_projecte>\d+)$', 'resum_facturacio_projecte',    name='resum_facturacio_projecte'),

    url(r'^moviments/$',                                     'llistat_moviments',            name='moviments'),
    url(r'^moviments/(?P<id_projecte>\d+)$',                 'llistat_moviments',            name='moviments'),
    url(r'^moviments/(?P<id_projecte>\d+)/tots/$',           'llistat_moviments',            kwargs=dict(tots=True), name='moviments'),
    url(r'^resum_liquidacio_trimestre/$',                     'resum_liquidacio_trimestre',            name='resum_liquidacio_trimestre'),
    url(r'^executar_autoliquidacio_trimestre/$',              'executar_autoliquidacio_trimestre',     name='executar_autoliquidacio_trimestre'),

    url(r'^llistat_projectes_autoocupats/$',                  'llistat_projectes_autoocupats',         name='llistat_projectes_autoocupats'),
    url(r'^executar_tancament_trimestre_projecte/$',          'executar_tancament_trimestre_projecte', name='executar_tancament_trimestre_projecte'),
    url(r'^executar_tancament_trimestre/$',                   'executar_tancament_trimestre',          name='executar_tancament_trimestre'),

    url(r'^facturacio_per_proveidor/$', 'volum_facturacio_empresa', kwargs=dict(tipus='proveidor'), name='facturacio_per_proveidor'),
    url(r'^facturacio_per_client/$',    'volum_facturacio_empresa', kwargs=dict(tipus='client'),    name='facturacio_per_client'),

    url(r'^importar_extracte_bancari/$',                  'importar_extracte_bancari',             name="importar_extracte_bancari"),
    url(r'^exportar_extracte_bancari/$',                  'exportar_extracte_bancari',             name="exportar_extracte_bancari"),
    url(r'^exportar_extracte_bancari/(?P<id>\d+)$',       'exportar_extracte_bancari',             name="exportar_extracte_bancari"),
    url(r'^llistat_moviments_extracte_descartats/tots/$', 'llistat_moviments_extracte_descartats', kwargs=dict(tots=True), name='llistat_moviments_descartats_tots'),
    url(r'^llistat_moviments_extracte_descartats/$',      'llistat_moviments_extracte_descartats', name='llistat_moviments_descartats'),

    url(r'^conciliacio_automatica_factures/$',
        'conciliacio_automatica_factures', name='conciliacio_automatica_factures'),

    url(r'^conciliacio_automatica_moviments_simples/$',
        'conciliacio_automatica_moviments_simples', name='conciliacio_automatica_moviments_simples'),

    url(r'^executar_conciliacio_moviments_simples/$',
        'executar_conciliacio_moviments_simples', name='executar_conciliacio_moviments_simples'),

    url(r'^conciliacio_manual/$',
        'conciliacio_manual', name='conciliacio_manual'),

    url(r'^conciliacio_manual/(?P<compte_projecte>COOP\d{4})$',
        'conciliacio_manual_projecte', name='conciliacio_manual_projecte'),

    url(r'^conciliacio_manual/(?P<numero_factura>\d{4}/\d{6})$',
        'conciliacio_manual_factura', name='conciliacio_manual_factura'),

    url(r'^executar_conciliacio_automatica_factura$',
        'executar_conciliacio_automatica_factura', name='executar_conciliacio_automatica_factura'),

    url(r'^descartar_moviment_extracte_bancari$',
        'descartar_moviment_extracte_bancari', name='descartar_moviment_extracte_bancari'),

    url(r'^llistat_aportacions_trimestre_projectes$',
        'llistat_aportacions_trimestre_projectes', name='llistat_aportacions_trimestre_projectes'),

    url(r'^exportar_projectes_per_comarca$',
        'exportar_projectes_per_comarca', name='exportar_projectes_per_comarca'),
    
    url(r'^exportar_projectes_per_liquidacio$',
        'exportar_projectes_per_liquidacio', name='exportar_projectes_per_liquidacio'),
    
    url(r'^derivar_exportacio_aportacions_csv$',
        'derivar_exportacio_aportacions_csv', name='derivar_exportacio_aportacions_csv'),
    url(r'^exportar_aportacions_csv/(?P<trimestre>\w{6})$',
        'exportar_aportacions_csv', name='exportar_aportacions_csv'),
    
    url(r'^derivar_exportacio_factures_csv$',
        'derivar_exportacio_factures_csv', name='derivar_exportacio_factures_csv'),
    url(r'^exportar_factures_emeses_csv/(?P<trimestre>\w{6})$',
        'exportar_factures_emeses_csv', name='exportar_factures_emeses_csv'),
    url(r'^exportar_factures_rebudes_csv/(?P<trimestre>\w{6})$',
        'exportar_factures_rebudes_csv', name='exportar_factures_rebudes_csv'),

)

socies/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'socies.views',
    url(r'^cerca_persones/$', 'cerca_persones', name='cerca_persones'),
)

facturacio/models.py
# coding=utf-8
import re

from datetime import timedelta
from decimal import Decimal

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.db import models, transaction
from django.db.models import Max, Sum

from gestioci.helpers import now
from projectes.models import ProjecteAutoocupat
from empreses.models import Empresa, Cooperativa
from socies.models import PersonaUsuaria, Persona
from gestioci.settings import auth_groups
from .helpers import calcular_trimestre


class TarifaQuotaTrimestral(models.Model):

    base_imposable_minima = models.DecimalField(max_digits=8, decimal_places=2)
    import_quota_trimestral = models.DecimalField(max_digits=8, decimal_places=2)
    data_vigor = models.DateField(verbose_name=u"data d'entrada en vigor")

    class Meta:
        verbose_name_plural = 'quotes trimestrals'


class Factura(models.Model):

    FORMA_PAGAMENT_EFECTIU = 'efectiu'
    FORMA_PAGAMENT_TRANSFERENCIA = 'transferencia'

    FORMES_DE_PAGAMENT = (
        (FORMA_PAGAMENT_EFECTIU, u"Cobrament al comptat"),
        (FORMA_PAGAMENT_TRANSFERENCIA, u"Ingrés al compte corrent de la cooperativa"),
    )

    projecte = models.ForeignKey(ProjecteAutoocupat)

    proveidor = models.ForeignKey(Empresa, related_name='factures_emeses')
    client = models.ForeignKey(Empresa, related_name='factures_rebudes')

    data = models.DateField()

    base_total = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    iva_total = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    import_total = models.DecimalField(default=0, max_digits=8, decimal_places=2)

    data_venciment = models.DateField(null=True, blank=True)
    forma_de_pagament = models.CharField(default=FORMA_PAGAMENT_EFECTIU, max_length=16, choices=FORMES_DE_PAGAMENT)

    observacions = models.TextField(max_length=4096, blank=True)
    
    def _actualitzar_camps_calculats(self):
        """
        * actualitza els camps calculats de Factura.
        * no crida a save() en acabar, pq aquesta funció s'ha de 'overload' a
        les classes que en deriven, FacturaEmesa i FacturaRebuda, i es allà a
        on s'espera que es cridi el save()
        """

        client_es_cooperativa = Cooperativa.objects.filter(pk=self.client_id).exists()
        proveidor_es_cooperativa = Cooperativa.objects.filter(pk=self.proveidor_id).exists()

        if client_es_cooperativa and proveidor_es_cooperativa:
            raise Exception(u"La factura és invàlida: el client i el proveïdor són cooperatives")

        if not (client_es_cooperativa or proveidor_es_cooperativa):
            raise Exception(u"La factura és invàlida: no implica cap cooperativa, ni com a client ni com a proveïdor")

        if not self.pertany_a_trimestre_obert():
            raise Exception(u"La factura no es pot editar: correspon a un trimestre que no esta obert")

        self.base_total = Decimal('0.00')
        self.iva_total = Decimal('0.00')
        self.import_total = Decimal('0.00')

        for l in self.liniafactura_set.all():
            self.base_total += l.base_total
            self.iva_total += l.iva_total
            self.import_total += l.import_total

    def usuari_pot_editar(self, user):

        try:
            persona = PersonaUsuaria.objects.filter(usuari=user).first().persona
            self.projecte.membres_de_referencia.get(pk=persona.pk)
            return True

        except PersonaUsuaria.DoesNotExist, Persona.DoesNotExist:
            return False

    def pertany_a_trimestre_obert(self):

        trimestre = Trimestre.trobar_trimestre(self.data)
        assert trimestre  # no s'hauria d'haver pogut crear una factura en un trimestre que no existeix

        return trimestre.obert

    def clean(self):
        # Don't allow an invoice in the future and in trimester that doesn't exists
        try:
            if (self.data > now().date()) and not self.pertany_a_trimestre_obert():
                raise ValidationError("No está permés introdüir factures en trimestres futurs")
        except:
            raise ValidationError("No está permés introdüir factures en trimestres futurs")
        
    def save(self, *args, **kwargs):
        if (self.client and self.client.pendent_de_revisio) or (self.proveidor and self.proveidor.pendent_de_revisio):
            raise Exception(u"La factura és invàlida: no pot implicar una empresa que no ha estat validada per GE")
        super(Factura, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = u"factures"


class SequenciaNumeroFacturaEmesa(models.Model):

    year = models.SmallIntegerField(primary_key=True)
    value = models.IntegerField()

    @staticmethod
    @transaction.atomic
    def incrementa_i_retorna_seguent_numero(data):
        sequencia = SequenciaNumeroFacturaEmesa.objects.select_for_update().get(year=data.year)
        sequencia.value += 1
        sequencia.save()
        return sequencia.value

    @staticmethod
    def crear_sequencies_necessaries():
        """
        inicialitza a 1 les seqüències per als propers anys;
        la idea és no haver d'inicialitzar la seqüència per cada any
        en el moment de generar la primera factura; com que els anys
        es creen per avançat, d'aquesta manera s'esquiva el problema
        de concurrència que requeriria un "lock" explícit que caldria
        en el supòsit que evitem d'aquesta manera.

        aquest mètode està pensat per ser cridat des d'un cron job.
        """
        years_in_advance = 5
        current_year = now().year
        farthest_year = SequenciaNumeroFacturaEmesa.objects.all().aggregate(Max('year'))['year__max']
        if farthest_year is None:
            farthest_year = current_year - 1
        for year in range(farthest_year + 1, max(current_year + years_in_advance, farthest_year) + 1):
            SequenciaNumeroFacturaEmesa.objects.create(year=year, value=0)


class FacturaEmesa(Factura):

    ESTAT_EMESA = 'emesa'
    ESTAT_COBRADA = 'cobrada'

    ESTATS = (
        (ESTAT_EMESA, u"Pendent de cobrar"),
        (ESTAT_COBRADA, u"Cobrada"),
    )

    numero = models.CharField(max_length=11, blank=True, null=True)
    estat = models.CharField(max_length=16, choices=ESTATS, default=ESTAT_EMESA)
    req_total = models.DecimalField(default=0, max_digits=8, decimal_places=2)  # recàrrec d'equivalència

    @transaction.atomic
    def assignar_numero_sequencia(self):
        n = SequenciaNumeroFacturaEmesa.incrementa_i_retorna_seguent_numero(self.data)
        self.numero = '%d/%06d' % (self.data.year, n)
        self.save()

    def save(self, actualitzar_dades=True, *args, **kwargs):
        if actualitzar_dades:
            self._actualitzar_camps_calculats()
            self.req_total = Decimal('0.00')
            for l in self.liniafactura_set.all():
                self.req_total += l.req_total
        super(FacturaEmesa, self).save(*args, **kwargs)

    def calcular_resums(self):

        linies = self.liniafactura_set

        resum_iva = linies.values('tipus_iva').annotate(base_total=Sum('base_total'), iva_total=Sum('iva_total')).order_by('tipus_iva')
        resum_req = linies.values('tipus_req').annotate(base_total=Sum('base_total'), req_total=Sum('req_total')).order_by('tipus_req')
        resum_totals = linies.aggregate(Sum('base_total'), Sum('iva_total'), Sum('req_total'))

        import_total = sum([resum_totals[k] for k in resum_totals.keys()])
        base_total = resum_totals['base_total__sum']
        iva_total = resum_totals['iva_total__sum']
        req_total = resum_totals['req_total__sum']

        assert import_total == self.import_total
        assert base_total == self.base_total
        assert iva_total == self.iva_total
        assert req_total == self.req_total

        if len(resum_req) == 1:
            if resum_req[0]['tipus_req'] == Decimal('0.00'):
                resum_req = None

        return resum_iva, resum_req, resum_totals

    def __unicode__(self):
        return "FacturaEmesa %d (%s)" % (self.id, self.numero)

    class Meta:
        verbose_name_plural = u"factures emeses"


class FacturaRebuda(Factura):

    ESTAT_REBUDA = 'rebuda'        # s'ha creat la factura al portal del soci
    ESTAT_ACCEPTADA = 'acceptada'  # s'ha rebut la factura a GE (en paper) i s'ha acceptat per la comptabilitat
    ESTAT_REBUTJADA = 'rebutjada'  # no s'ha rebut a GE i/o s'ha considerat que no és cap factura vàlida

    ESTATS = (
        (ESTAT_REBUDA, u"Pendent de revisió"),
        (ESTAT_ACCEPTADA, u"Acceptada"),
        (ESTAT_REBUTJADA, u"Rebutjada"),
    )

    numero = models.CharField(max_length=64)

    irpf_total = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    tipus_irpf = models.DecimalField(default=0, max_digits=4, decimal_places=2,
                                     verbose_name=u"retenció per l'IRPF",
                                     help_text=u"en tant percent (%)")

    estat = models.CharField(max_length=16, choices=ESTATS, default=ESTAT_REBUDA)
    vist_i_plau_usuaria = models.ForeignKey(User, blank=True, null=True, related_name='+')
    vist_i_plau_data = models.DateTimeField(blank=True, null=True)
    vist_i_plau_observacions = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        self._actualitzar_camps_calculats()
        self.irpf_total = ((self.base_total * self.tipus_irpf) / 100).quantize(Decimal('0.01'))
        self.import_total -= self.irpf_total
        super(FacturaRebuda, self).save(*args, **kwargs)

    def calcular_resums(self):

        linies = self.liniafactura_set

        resum_iva = linies.values('tipus_iva').annotate(base_total=Sum('base_total'), iva_total=Sum('iva_total')).order_by('tipus_iva')
        resum_totals = linies.aggregate(Sum('base_total'), Sum('iva_total'))

        import_total = sum([resum_totals[k] for k in resum_totals.keys()]) - self.irpf_total

facturacio/templates/facturacio/conciliacio_automatica_factures.html
{% extends "simple.html" %}
{% load gci_tags %}

{% block titol_a_capcalera %}Conciliació automàtica de moviments a l'extracte bancari{% endblock %}

{% block content %}


<style>
    .ac { text-align: center; }
    .ar { text-align: right; }
    .match_header { background-color: #ccccff; text-align: center; }
    .observacions_ok { color:darkgreen; }
    .observacions_warning { color:darkorange; }
    .observacions_error { color:red; }
{#    tr.coincidencia { border: 1px solid black; }#}
    .ok { color: darkgreen; }
    .nok {  color: darkred; }
    .ok li {  font-size: 75%; }
    .nok li { font-size: 75%; }
</style>


<fieldset>
    <legend>
        {{ coincidencies|length }}
        coincidènci{{ coincidencies|length|pluralize:"a,es" }}
{#        clar{{ coincidencies|length|pluralize:"a,es" }}#}
    </legend>

    {% if coincidencies %}


        <table>

            {% for coincidencia in coincidencies %}
            {% with m=coincidencia.moviment_extracte f=coincidencia.factura observacions=coincidencia.observacions %}

        <tr><td>

            <table>
                <tr>
                    <th colspan="2" class="match_header">Moviment</th>
                    <th colspan="2" class="match_header">Factura</th>
                </tr>
                <tr>
                    <th>Compte</th><td>{{ m.compte }}</td>
                    <th>Cooperativa</th><td>{{ f.proveidor }}</td>

                </tr>
                <tr>
                    <th>Número de factura</th><td>{{ m.numero_factura }}</td>
                    <th>Número</th><td>{{ f.numero }}</td>
                </tr>
                <tr>
                    <th>Projecte</th><td>{{ m.compte_projecte }}</td>
                    <th>Projecte</th><td>{{ f.projecte }}</td>
                </tr>
                <tr>
                    <th>Concepte</th><td>{{ m.concepte }}</td>
                    <th>Client</th><td>{{ f.client }}</td>

                </tr>
                <tr>
                    <th>Import</th><td>{% currency_value m.quantitat %}</td>
                    <th>Import</th><td>{% currency_value f.import_total %}</td>
                </tr>
                <tr>
                    <th>Data</th><td>{{ m.data|date:'Y-m-d' }}</td>
                    <th>Data de venciment</th><td>{{ f.data_venciment|date:'Y-m-d' }}</td>
                </tr>
                <tr>
                    <th>Tipus</th><td>{{ m.tipus }}</td>
                    <th>Data d'emissió</th><td>{{ f.data|date:'Y-m-d' }}</td>
                </tr>
                <tr>
                    <th>Estat</th><td>{{ m.get_estat_display }}</td>
                    <th>Estat</th><td>{{ f.get_estat_display }}</td>
                </tr>
                <tr>
                    <th>Comentaris</th><td>{{ m.comentaris }}</td>
                    <th>Forma de pagament</th><td>{{ f.get_forma_de_pagament_display }}</td>
                </tr>
                <tr>
                    <td colspan="4">
                        <table>
                            <tr>
                                <td rowspan="2" style="vertical-align: top">Observacions:
                                    <ul>
                                        {% for o in observacions %}<li class="observacions_{{ o.0 }}">{{ o.1 }}</li>{% endfor %}
                                    </ul>
                                </td>
                                <td>
                                    <div id="forms_{{ m.id }}">
                                        <form onsubmit="bgSubmit(event)" method="post" action="{% url "facturacio:executar_conciliacio_automatica_factura" %}">
                                        {% csrf_token %}
                                        {% form_field form.comentaris %}
                                            <textarea style="display:none" name="conciliacio_automatica_observacions">{{ coincidencia.observacions_compactes }}</textarea>
                                            <input type="hidden" name="moviment_extracte_id" value="{{ m.id }}">
                                            <input type="hidden" name="factura_id" value="{{ f.id }}">
                                            <button style="background-color:darkgreen"><i class="fa fa-fw fa-check-square"></i> conciliar moviment i factura</button>
                                        </form>
                                        <form onsubmit="bgSubmit(event)" method="post" action="{% url "facturacio:descartar_moviment_extracte_bancari" %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="moviment_extracte_id" value="{{ m.id }}">
                                            <button style="background-color:darkred"><i class="fa fa-fw fa-exclamation-circle"></i> descartar moviment</button>
                                        </form>
                                    </div>
                                    <div id="resultat_{{ m.id }}" style="display:none;"></div>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>

        </td></tr>

            {% endwith %}
            {% endfor %}

         </table>

        {% else %}

            No s'ha trobat cap coincidència clara.

        {% endif %}

</fieldset>


<script>

var request = false; // we will try to avoid parallel submits

function bgSubmit(event) {

    event.preventDefault();

    var $form = $(event.target);
    var formData = new FormData();

    $form.find(':input').each(function() {
        var name = $(this).attr('name');
        var value = $(this).val();
        formData.append(name, value);
    });

    http_post($form.attr('action'), formData)
}

function http_post(url, formData) {

    if (request) {
        request.abort();
    }

    request = new XMLHttpRequest();

    request.open("POST", url, true);
{# TODO review actual request headers and figure out if these are already present or if they can help in any way #}
{#    request.setRequestHeader("Content-type", "application/x-www-form-urlencoded");#}
{#    request.setRequestHeader("Content-length", params.length);#}
{#    request.setRequestHeader("Connection", "close");#}

    request.onreadystatechange = function () { // will be called when the state changes.
        if (request.readyState == 4 && request.status == 200) {
            resposta_rebuda(request.responseText);
            request = false;
        }
    };

    request.send(formData);
}

function resposta_rebuda(responseText) {
    var resultat = JSON.parse(responseText);
    var moviment_extracte_id = resultat['moviment_extracte_id'];
    var $forms = $('#forms_' + moviment_extracte_id);
    var $display = $('#resultat_' + moviment_extracte_id);
    $forms.hide();
    $display.append(makeUL(resultat['report']));
    $display.addClass(resultat['result']);
    $display.show();
}

function makeUL(array) {
    // http://stackoverflow.com/questions/11128700/create-a-ul-and-fill-it-based-on-a-passed-array
    var list = document.createElement('ul');
    for(var i = 0; i < array.length; i++) {
        var item = document.createElement('li');
        item.appendChild(document.createTextNode(array[i]));
        list.appendChild(item);
    }
    return list;
}

</script>


{%  endblock %}

facturacio/templates/facturacio/crear_factura_emesa.html
{% extends "simple.html" %}
{% load gci_tags %}

{#{% block titol_a_capcalera %}#}
{#{% endblock %}#}

{% block content %}

{# this should be above, inside titol_a_capcalera #}
<h1>Emissió d'una nova factura</h1>
{# end titol_a_capcalera #}

{% block explicacio_pas %}
    <div class="panel">
        <ul>
            {% if form %}
                <li>Començareu creant una factura «esborrall»; La factura definitiva es genera al final d'aquest procés.</li>
                <li>Trieu el client i la data d'emissió.</li>
                <li>Proveu a començar a escriure al camp de sota el NIF o el nom de l'empresa.</li>
                <li>Si no hi surt, l'haureu de <a href="{% url "facturacio:buscar_empresa" kind="client" %}">buscar o donar d'alta</a>.</li>
                <li>La data de la factura ha de correspondre al trimestre en curs, o a l'anterior, si encara no està tancat.</li>
            {% else %}
                <li>No hi teniu cap client a la vostra llista; L'haureu de <a href="{% url "facturacio:buscar_empresa" kind="client" %}">buscar o donar d'alta</a>.</li>
            {% endif %}
        </ul>
    </div>
{% endblock %}

{% if form %}
    <form method="POST">
      {% csrf_token %}
      {{ form.non_field_errors }}
        {% form_field form.client %}
        {% form_field form.data %}
	{% form_field form.observacions %}
        <button class="radius button" type="submit">Crear factura esborrall</button>
    </form>
{% endif %}

{% endblock %}

facturacio/templates/facturacio/crear_factura_rebuda.html
{% extends "simple.html" %}
{% load gci_tags %}

{#{% block titol_a_capcalera %}#}
{#{% endblock %}#}

{% block content %}

{# this should be above, inside titol_a_capcalera #}
<h1>Entrada d'una factura rebuda</h1>
{# end titol_a_capcalera #}

{% block explicacio_pas %}
    <div class="panel">
        <ul>
            {% if form %}
                <li>Tingueu present que <b>un <em>tiquet</em> no és una factura</b>.</li>
                <li>Trieu el proveïdor i la data d'emissió.</li>
                <li>Proveu a començar a escriure al camp de sota el NIF o el nom de l'empresa.</li>
                <li>Si no hi surt, l'haureu de <a href="{% url "facturacio:buscar_empresa" kind="proveidor" %}">buscar o donar d'alta</a>.</li>
                <li>La data de la factura ha de correspondre al trimestre en curs, o a l'anterior, si encara no està tancat.</li>
            {% else %}
                <li>No hi teniu cap proveïdor a la vostra llista; L'haureu de <a href="{% url "facturacio:buscar_empresa" kind="proveidor" %}">buscar o donar d'alta</a>.</li>
            {% endif %}
        </ul>
    </div>
{% endblock %}

{% if form %}
    <form method="POST">
        {% csrf_token %}
        {% form_field form.proveidor %}
        {% form_field form.data %}
        {% form_field form.numero %}
        <button class="radius button" type="submit">Crear factura</button>
    </form>
{% endif %}

{% endblock %}