gestioci/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = patterns(
    '',

    # Default Django Auth
    # https://docs.djangoproject.com/en/1.8/topics/auth/default/#built-in-auth-views
    url(r'^accounts/', include([
        url(r'^login/$', auth_views.login, name='login'),
        url(r'^logout/$', auth_views.logout, {'next_page': '/accounts/login/'}, name='logout'),

        url(r'^password/', include([
            url(r'^change/$', auth_views.password_change, name='password_change'),
            url(r'^change/done/$', auth_views.password_change_done, name='password_change_done'),

            url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
            url(r'^reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
            url(r'^reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
            url(r'^reset/$', auth_views.password_reset, { 'html_email_template_name': 'registration/password_reset_email.html' }, name='password_reset'),
        ])),
    ])),


    # Apps
    url(r'^socies/alta/', include('alta_socies.urls', namespace='alta_socies')),
    url(r'^socies/',      include('socies.urls', namespace='socies')),
    url(r'^facturacio/',  include('facturacio.urls', namespace='facturacio')),
    url(r'^projectes/',   include('projectes.urls', namespace='projectes')),

    url(r'^admin/',       include(admin.site.urls)),

    url(r'^ge/$',          'inici.views.dashboard_gestio_economica', name='dashboard_gestio_economica'),
    url(r'^pao/$',         'facturacio.views.dashboard_facturacio',  name='dashboard_projecte_autoocupat'),
    url(r'^style-guide/$', 'inici.views.styleguide',                 name='styleguide'),

    url(r'^$',            'inici.views.inici',                      name='inici'),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns(
        '',
        (
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

# Implement docutils features
if settings.ENV == 'development':
    urlpatterns += patterns(
        '',
        ( r'^admin/doc/', include('django.contrib.admindocs.urls')),
        )

projectes/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(

    'projectes.views',

    url(r'^resum_projecte_autoocupat/(?P<id_projecte>\d+)$', 'resum_projecte_autoocupat', name='resum_projecte_autoocupat'),

    url(r'^editar_cooperativa_projecte/(?P<id_projecte>\d+)$', 'editar_cooperativa_projecte', name='editar_cooperativa_projecte'),

    url(r'^editar_contacte_projecte/(?P<id_projecte>\d+)$', 'editar_contacte_projecte', name='editar_contacte_projecte'),

    url(r'^editar_descripcio_projecte/(?P<id_projecte>\d+)$', 'editar_descripcio_projecte', name='editar_descripcio_projecte'),

    url(r'^editar_adreca_projecte/(?P<id_projecte>\d+)/(?P<id_adreca>\d+)$', 'editar_adreca_projecte', name='editar_adreca_projecte'),
)

socies/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'socies.views',
    url(r'^cerca_persones/$', 'cerca_persones', name='cerca_persones'),
)

projectes/forms.py
from django import forms

from empreses.models import Cooperativa
from socies.models import AdrecaProjecteAutoocupat
from .models import ProjecteAutoocupat


class FormulariEditarCooperativa(forms.Form):

    cooperativa = forms.ModelChoiceField(
        queryset=Cooperativa.objects.all(),
        label=u"Cooperativa a assignat"
    )


class FormulariEditarContactePAO(forms.ModelForm):

    class Meta:
        model = ProjecteAutoocupat
        fields = ['email', 'telefon', 'website']


class FormulariEditarDescripcioPAO(forms.ModelForm):

    class Meta:
        model = ProjecteAutoocupat
        fields = ['descripcio']


class FormulariEditarAdrecaPAO(forms.ModelForm):

    class Meta:
        model = AdrecaProjecteAutoocupat
        fields = ['provincia', 'comarca', 'poblacio', 'codi_postal', 'adreca']

projectes/views.py
# coding=utf-8
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from facturacio.helpers import trobar_projectes_usuari
from gestioci.settings import auth_groups
from projectes.models import ProjecteAutoocupat
from socies.models import AdrecaProjecteAutoocupat

from .forms import FormulariEditarCooperativa, FormulariEditarContactePAO, \
    FormulariEditarDescripcioPAO, FormulariEditarAdrecaPAO


@login_required
def resum_projecte_autoocupat(request, id_projecte):

    projecte = ProjecteAutoocupat.objects.get(id=id_projecte)

    is_membre_de_referencia = projecte in trobar_projectes_usuari(request.user)
    is_responsable_facturacio = request.user.groups.filter(name=auth_groups.RESPONSABLES_FACTURACIO).exists()

    if not is_membre_de_referencia and not is_responsable_facturacio:
        messages.success(request, u"No tens permís per accedir a aquesta informació")
        return redirect('inici')

    return render(
        request,
        'projectes/resum_projecte_autoocupat_base.html',
        dict(
            p=projecte,
        )
    )


@login_required
def editar_adreca_projecte(request, id_projecte, id_adreca):

    projecte = ProjecteAutoocupat.objects.get(id=id_projecte)

    is_responsable_facturacio = request.user.groups.filter(name=auth_groups.RESPONSABLES_FACTURACIO).exists()
    
    if not is_responsable_facturacio:
        messages.success(request, u"No tens permís per accedir a aquesta informació")
        return redirect('inici')

    adreca = AdrecaProjecteAutoocupat.objects.get(id=id_adreca)
    
    if request.method == 'POST':
        form = FormulariEditarAdrecaPAO(instance=adreca, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, u"S'ha actualitzat l'adreça correctament")
            return redirect('projectes:resum_projecte_autoocupat', id_projecte=projecte.id)

    form = FormulariEditarAdrecaPAO(instance=adreca)

    return render(
        request,
        'projectes/editar_adreca_projecte.html',
        {
            'p': projecte,
            'form': form,
        }
    )


@login_required
def editar_descripcio_projecte(request, id_projecte):

    projecte = ProjecteAutoocupat.objects.get(id=id_projecte)

    is_responsable_facturacio = request.user.groups.filter(name=auth_groups.RESPONSABLES_FACTURACIO).exists()
    
    if not is_responsable_facturacio:
        messages.success(request, u"No tens permís per accedir a aquesta informació")
        return redirect('inici')

    if request.method == 'POST':
        form = FormulariEditarDescripcioPAO(instance=projecte, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, u"S'ha actualitzat la descripció correctament")
            return redirect('projectes:resum_projecte_autoocupat', id_projecte=projecte.id)

    form = FormulariEditarDescripcioPAO(instance=projecte)

    return render(
        request,
        'projectes/editar_descripcio_projecte.html',
        {
            'p': projecte,
            'form': form,
        }
    )


@login_required
def editar_contacte_projecte(request, id_projecte):

    projecte = ProjecteAutoocupat.objects.get(id=id_projecte)

    is_responsable_facturacio = request.user.groups.filter(name=auth_groups.RESPONSABLES_FACTURACIO).exists()
    
    if not is_responsable_facturacio:
        messages.success(request, u"No tens permís per accedir a aquesta informació")
        return redirect('inici')

    if request.method == 'POST':
        form = FormulariEditarContactePAO(instance=projecte, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, u"S'ha actualitzat el contacte correctament")
            return redirect('projectes:resum_projecte_autoocupat', id_projecte=projecte.id)

    form = FormulariEditarContactePAO(instance=projecte)

    return render(
        request,
        'projectes/editar_contacte_projecte.html',
        {
            'p': projecte,
            'form': form,
        }
    )


@login_required
def editar_cooperativa_projecte(request, id_projecte):

    projecte = ProjecteAutoocupat.objects.get(id=id_projecte)

    is_responsable_facturacio = request.user.groups.filter(name=auth_groups.RESPONSABLES_FACTURACIO).exists()
    
    if not is_responsable_facturacio:
        messages.success(request, u"No tens permís per accedir a aquesta informació")
        return redirect('inici')

    if request.method == 'POST':
        form = FormulariEditarCooperativa(data=request.POST)
        if form.is_valid():
            projecte.cooperativa_assignada = form.cleaned_data['cooperativa']
            projecte.save()
            messages.success(request, u"S'ha actualitzat la cooperativa correctament")
            return redirect('projectes:resum_projecte_autoocupat', id_projecte=projecte.id)

    form = FormulariEditarCooperativa(
        initial={
            'cooperativa': projecte.cooperativa_assignada,
        }
    )

    return render(
        request,
        'projectes/editar_cooperativa_projecte.html',
        {
            'p': projecte,
            'form': form,
        }
    )
   

projectes/templates/projectes/editar_adreca_projecte.html
{% extends "projectes/resum_projecte_autoocupat_base.html" %}
{% load gci_tags %}

{% block adreca %}


<form method="post">
{% csrf_token %}

<table>
  <tr><th>{{ form.provincia.label }}</th><td>{{ form.provincia }}</td></tr>
  <tr><th>{{ form.comarca.label }}</th><td>{{ form.comarca }}</td></tr>
  <tr><th>{{ form.poblacio.label }}</th><td>{{ form.poblacio }}</td></tr>
  <tr><th>{{ form.codi_postal.label }}</th><td>{{ form.codi_postal }}</td></tr>
  <tr><th>{{ form.adreca.label }}</th><td>{{ form.adreca }}</td></tr>
</table>

<button class="button radius" name="Desar" type="submit">Desar</button>

</form>
{% endblock %}

projectes/templates/projectes/editar_contacte_projecte.html
{% extends "projectes/resum_projecte_autoocupat_base.html" %}
{% load gci_tags %}

{% block contacte %}


<form method="post">
{% csrf_token %}

<table>
  <tr><th>{{ form.email.label }}</th><td>{{ form.email }}</td></tr>
  <tr><th>{{ form.telefon.label }}</th><td>{{ form.telefon }}</td></tr>
  <tr><th>{{ form.website.label }}</th><td>{{ form.website }}</td></tr>
</table>

<button class="button radius" name="Desar" type="submit">Desar</button>

</form>
{% endblock %}

projectes/templates/projectes/editar_cooperativa_projecte.html
{% extends "projectes/resum_projecte_autoocupat_base.html" %}
{% load gci_tags %}

{% block cooperativa %}


<form method="post">
{% csrf_token %}

<table>
  <tr><th>{{ form.cooperativa.label }}</th><td>{{ form.cooperativa }}</td></tr>
</table>

<button class="button radius" name="Desar" type="submit">Desar</button>

</form>
{% endblock %}

projectes/templates/projectes/editar_descripcio_projecte.html
{% extends "projectes/resum_projecte_autoocupat_base.html" %}
{% load gci_tags %}

{% block descripcio %}


<form method="post">
{% csrf_token %}

<table>
  <tr><th>{{ form.descripcio.label }}</th><td>{{ form.descripcio }}</td></tr>
</table>

<button class="button radius" name="Desar" type="submit">Desar</button>

</form>
{% endblock %}

projectes/templates/projectes/resum_projecte_autoocupat_base.html
{% extends "simple.html" %}

{% block content %}

    <h1>{{ p.nom }}</h1>
    <div class="label"> {{ p.tipus }} </div>
    {% if p.es_paic %}<div class="label"> PAIC </div>{% endif %}
    {% if p.te_comerc_electronic %}<div class="label"> Comerç Electronic </div>{% endif %}
    {% if p.mercat_virtual %}<div class="label"> Mercat Virtual </div>{% endif %}
    {% if p.te_productes_ecologics %}<div class="label"> Productes Ecologics </div>{% endif %}
    {% if p.expositors %}<div class="label"> Expositors </div>{% endif %}
    {% if p.transversal %}<div class="label"> Ex-Transversal </div>{% endif %}


    <h2>Cooperativa assignada <a href="{% url 'projectes:editar_cooperativa_projecte' id_projecte=p.id %}" class="label small radius secondary">Editar</a></h2>
{% block cooperativa %}    
    <table>
      <tr><th>NIF</th><td>{{ p.cooperativa_assignada.nif }}</td></tr>
      <tr><th>Nom Fiscal</th><td>{{ p.cooperativa_assignada.nom_fiscal }}</td></tr>
    </table>
{% endblock cooperativa %}

    <h2>Contacte <a href="{% url 'projectes:editar_contacte_projecte' id_projecte=p.id %}" class="label small radius secondary">Editar</a></h2>
{% block contacte %}    
    <table>
        <tr><th>Compte iCES</th><td>{{ p.compte_ces_assignat }}</td></tr>
        <tr><th>Email</th><td>{{ p.email }}</td></tr>
        <tr><th>Telèfon</th><td>{{ p.telefon }}</td></tr>
        <tr><th>Web</th><td>{{ p.website }}</td></tr>
    </tr>
    </table>
{% endblock contacte %}

    <h2>Membre{{ p.membres_de_referencia.count|pluralize }} de referència</h2>
    <table>
    <tr>
        <th>Nom</th><th>Email</th><th>Telèfon</th><th>Compte</th>
    </tr>
    {% for m in p.membres_de_referencia.all %}
        <tr>
            <td>{{ m.nom_sencer_sense_email }}</td>
            <td>{{ m.email }}</td>
            <td>{{ m.telefon }}</td>
            <td>{{ m.compte_integralces }}</td>
        </tr>
    {% endfor %}
    </table>

    <h2>Adreçes</h2>

    {% for adreca in p.adreces.all %}
    <a href="{% url 'projectes:editar_adreca_projecte' id_projecte=p.id id_adreca=adreca.id %}" class="label small radius secondary">Editar</a>
    {% block adreca %}
    <table>
      <tr><th>Provincia</th><td>{{ adreca.provincia }}</td></tr>
      <tr><th>Comarca</th><td>{{ adreca.comarca }}</td></tr>
      <tr><th>Població</th><td>{{ adreca.poblacio }}</td></tr>
      <tr><th>Codi Postal</th><td>{{ adreca.codi_postal }}</td></tr>
      <tr><th>Adreça</th><td>{{ adreca.adreca }}</td></tr>
    </table>
    {% endblock adreca %}
    {% endfor %}


    <h2>Descripció <a href="{% url 'projectes:editar_descripcio_projecte' id_projecte=p.id %}" class="label small radius secondary">Editar</a></h2>
{% block descripcio %}
    <div style="padding-left:20px; padding-right:20px; padding-bottom:20px;"><pre>{{ p.descripcio }}</pre></div>
{% endblock descripcio %}
{% endblock content %}