alta_socies/urls.py
from django.conf.urls import patterns, include, url

from .views import SessioMonedaListView, SessioMonedaCreateView
from .views import SessioAcollidaListView, SessioAcollidaCreateView, \
    SessioAcollidaUpdateView, SessioMonedaUpdateView
from .views import ProcesAltaAutoocupatDetailView

urlpatterns = patterns(

    'alta_socies.views',


    # ------------
    # ALTRES ALTES
    # ------------

    url(r'^sociaafi/llistat/$', 'llistat_socies_afins', name='llistat_socies_afins'),
    
    url(r'^cooperativa/habilitats/$', 'llistat_filtre_habilitats', name='llistat_socies_habilitats'),
    
    url(r'^cooperativa/llistat/$', 'llistat_socia_cooperativa', name='llistat_socia_cooperativa'),
    
    url(r'^cooperativa/llistat_pendents/euros/$', 'llistat_socies_pendents_euro', name='llistat_socies_pendents_euro'),

    url(r'^cooperativa/llistat_pendents/ecos/$', 'llistat_socies_pendents_eco', name='llistat_socies_pendents_eco'),

    url(r'^cooperativa/llistat_pendents/hores/$', 'llistat_socies_pendents_temp', name='llistat_socies_pendents_temp'),

    url(r'^cooperativa/validar/(?P<id_socia>\d+)/$', 'validar_socia_pendent', name='validar_socia_pendent'),
    
    url(r'^cooperativa/dades_personals/$', 'proces_alta_socia_cooperativa_dades_personals', name='alta_socia_cooperativa_dades_personals'),

    url(r'cooperativa/info/(?P<id_socia>\d+)/$', 'dades_socia_cooperativa', name='dades_socia_cooperativa'),

    url(r'cooperativa/editar/(?P<id_socia>\d+)/$', 'editar_socia_cooperativa', name='editar_socia_cooperativa'),

    url(r'^cooperativa/dades_alta/$', 'proces_alta_socia_cooperativa_dades_alta', name='alta_socia_cooperativa_dades_alta'),

    url(r'^cooperativa/dades_adreca/$', 'proces_alta_socia_cooperativa_dades_adreca', name='alta_socia_cooperativa_dades_adreca'),
    
    url(r'^collectiu/dades_generals/$', 'proces_alta_projecte_collectiu_dades_generals', name='collectiu_dades_generals'),

    url(r'^collectiu/dades_concretes/$', 'proces_alta_projecte_collectiu_dades_concretes', name='collectiu_dades_concretes'),

    url(r'^collectiu/socies_afins/$', 'proces_alta_projecte_collectiu_socies_afins', name='collectiu_socies_afins'),

    url(r'^collectiu/llistat/$', 'llistat_projecte_collectiu', name='llistat_projecte_collectiu'),
    
    url(r'^collectiu/llistat_pendents/euros/$', 'llistat_projectes_pendents_euro', name='llistat_projectes_pendents_euro'),

    url(r'^collectiu/llistat_pendents/ecos/$', 'llistat_projectes_pendents_eco', name='llistat_projectes_pendents_eco'),

    url(r'^collectiu/llistat_pendents/hores/$', 'llistat_projectes_pendents_temp', name='llistat_projectes_pendents_temp'),

    url(r'^collectiu/validar/(?P<id_projecte>\d+)/$', 'validar_projecte_pendent', name='validar_projecte_pendent'),

    url(r'^collectiu/editar/dades_generals/(?P<id_projecte>\d+)/$', 'editar_dades_generals_projecte', name='editar_dades_generals_projecte'),

    url(r'^collectiu/editar/dades_adreca/(?P<id_projecte>\d+)/$', 'editar_dades_adreca_projecte', name='editar_dades_adreca_projecte'),

    url(r'^collectiu/editar/socies_afins/(?P<id_projecte>\d+)/$', 'editar_socies_afins_projecte', name='editar_socies_afins_projecte'),
    
    url(r'^collectiu/info/(?P<id_projecte>\d+)/$', 'dades_projecte_collectiu', name='dades_projecte_collectiu'),

    url(r'^llibre/socies/$', 'exportar_llibre_integral_socies', name='exportar_llibre_integral_socies'),

    url(r'^llibre/socies_afins/$', 'exportar_llibre_integral_socies_afins', name='exportar_llibre_integral_socies_afins'),

    
    # -----------------
    # SOCIS AUTOOCUPATS
    # -----------------

    url(r'^rebutjar_proces_alta/(?P<id_proces>\d+)/$', 'rebutjar_proces_alta_autoocupat', name='rebutjar_proces'),

    url(r'^exportar_a_csv/$', 'exportar_a_csv', name='exportar_a_csv'),

    url(r'^autoocupat/resum/(?P<pk>\d+)/$', ProcesAltaAutoocupatDetailView.as_view(), name='resum_proces_alta_projecte_autoocupat'),

    url(r'^editar_sessio_moneda/(?P<pk>\d+)/$', SessioMonedaUpdateView.as_view(), name='editar_sessio_moneda'),

    url(r'^editar_sessio_acollida/(?P<pk>\d+)/$', SessioAcollidaUpdateView.as_view(), name='editar_sessio_acollida'),

    url(r'^llistat_sessio_acollida', SessioAcollidaListView.as_view(), name='llistat_sessio_acollida'),

    url(r'^crear_sessio_acollida', SessioAcollidaCreateView.as_view(), name='crear_sessio_acollida'),

    url(r'^llistat_sessio_moneda', SessioMonedaListView.as_view(), name='llistat_sessio_moneda'),

    url(r'^crear_sessio_moneda', SessioMonedaCreateView.as_view(), name='crear_sessio_moneda'),

    url(r'^generador_sessions/$',
        'generar_sessions',
        name='generador_sessions'),

    url(r'^sessions_del_mes/(?P<tipus>\w+)(/(?P<year>\d\d\d\d)/(?P<month>\d\d?))?$',
        'sessions_del_mes',
        name='sessions_del_mes'),

    url(r'^autoocupat/$',
        'proces_alta_projecte_autoocupat',
        name='proces_alta_projecte_autoocupat'),

    url(r'^autoocupat/(?P<id_proces>\d+)/$',
        'proces_alta_projecte_autoocupat',
        name='proces_alta_projecte_autoocupat'),

    url(r'^autoocupat/(?P<id_proces>\d+)/(?P<pas>\d+)/$',
        'proces_alta_projecte_autoocupat',
        name='proces_alta_projecte_autoocupat'),

    url(r'^autoocupat/llista-tasques/(?P<id_proces>\d+)/$',
        'proces_alta_projecte_autoocupat_llista_de_tasques',
        name='proces_alta_projecte_autoocupat-llista_de_tasques'),

    url(r'^autoocupat/llistat_proces_alta_autoocupat/$',
        'llistat_proces_alta_autoocupat',
        name='llistat_proces_alta_autoocupat'),

    url(r'^autoocupat/control-qualitat/$',
        'llistat_proces_alta_projecte_autoocupat_revisio_descripcions',
        name='llistat_proces_alta_projecte_autoocupat_revisio_descripcions'),

    url(r'^estadistiques_proces_alta_projecte_autoocupat/?$',
        'estadistiques_proces_alta_projecte_autoocupat',
        name='estadistiques_proces_alta_projecte_autoocupat'),

    url(r'^reassignacio_proces_alta_autoocupat/?$',
        'reassignacio_proces_alta_autoocupat',
        name='reassignacio_proces_alta_autoocupat'),

)

gestioci/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = patterns(
    '',

    # Default Django Auth
    # https://docs.djangoproject.com/en/1.8/topics/auth/default/#built-in-auth-views
    url(r'^accounts/', include([
        url(r'^login/$', auth_views.login, name='login'),
        url(r'^logout/$', auth_views.logout, {'next_page': '/accounts/login/'}, name='logout'),

        url(r'^password/', include([
            url(r'^change/$', auth_views.password_change, name='password_change'),
            url(r'^change/done/$', auth_views.password_change_done, name='password_change_done'),

            url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
            url(r'^reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
            url(r'^reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
            url(r'^reset/$', auth_views.password_reset, { 'html_email_template_name': 'registration/password_reset_email.html' }, name='password_reset'),
        ])),
    ])),


    # Apps
    url(r'^socies/alta/', include('alta_socies.urls', namespace='alta_socies')),
    url(r'^socies/',      include('socies.urls', namespace='socies')),
    url(r'^facturacio/',  include('facturacio.urls', namespace='facturacio')),
    url(r'^projectes/',   include('projectes.urls', namespace='projectes')),

    url(r'^admin/',       include(admin.site.urls)),

    url(r'^ge/$',          'inici.views.dashboard_gestio_economica', name='dashboard_gestio_economica'),
    url(r'^pao/$',         'facturacio.views.dashboard_facturacio',  name='dashboard_projecte_autoocupat'),
    url(r'^style-guide/$', 'inici.views.styleguide',                 name='styleguide'),

    url(r'^$',            'inici.views.inici',                      name='inici'),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns(
        '',
        (
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

# Implement docutils features
if settings.ENV == 'development':
    urlpatterns += patterns(
        '',
        ( r'^admin/doc/', include('django.contrib.admindocs.urls')),
        )

socies/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'socies.views',
    url(r'^cerca_persones/$', 'cerca_persones', name='cerca_persones'),
)

alta_socies/templates/alta_socies/cita_nou_projecte_autoocupat.html
{%  extends "gci.html" %}

{% block main %}
<h1>Assignació de cites per alta de projecte autoocupat</h1>
<form name="cita_nou_projecte_autoocupat" method="POST">{% csrf_token %}

    <table>
        {{ form_projecte.as_table }}
        {{ form_cites.as_table }}
    </table>

    <input type="submit" value="enregistrar">

</form>

{% endblock %}

alta_socies/templates/alta_socies/dades_projecte_collectiu.html
{% extends 'layout.html' %}
{% load gci_tags %}

{% block content %}
<div class="row">
  <div class="medium-10 columns">
    <h1>{{ title }}</h1>
  </div>
  <div class="medium-2 columns">

  </div>
</div>
<div class="row">
  <div class="medium-12 columns">
    <fieldset>
      <legend>
	Dades Generals
	<a href="{% url 'alta_socies:editar_dades_generals_projecte' projecte.id %}" class="label radius success">Editar</a>
      </legend>
      <div class="row">
	<div class="medium-3 columns">
	  <strong>Nom: </strong><p>{{ projecte.nom }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Website: </strong><p>{{ projecte.website }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Email: </strong><p>{{ projecte.email }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Telefon: </strong><p>{{ projecte.telefon }}</p>
	</div>
      </div>
      <div class="row">
	<div class="medium-2 columns">
	  <strong>Tipus: </strong><p>{{ projecte.get_tipus_projecte_display }}</p>
	</div>
	<div class="medium-10 columns">
	  <strong>Descripció: </strong><p>{{ projecte.descripcio }}</p>
	</div>
      </div>
    </fieldset>
    <fieldset>
      <legend>
	Adreça
	<a href="{% url 'alta_socies:editar_dades_adreca_projecte' projecte.id %}" class="label radius success">Editar</a>
      </legend>
      <div class="row">
	<div class="medium-3 columns">
	  <strong>País: </strong><p>{{ projecte.adreca.pais }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Província: </strong><p>{{ projecte.adreca.provincia }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Comarca: </strong><p>{{ projecte.adreca.comarca }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Població: </strong><p> {{ projecte.adreca.poblacio }}</p>
	</div>
      </div>
      <div class="row">
	<div class="medium-9 columns">
	  <strong>Adreça: </strong><p>{{ projecte.adreca.adreca }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Codi Postal: </strong><p>{{ projecte.adreca.codi_postal }}</p>
	</div>
      </div>
    </fieldset>
    <fieldset>
      <legend>
	Dades cooperatives
      </legend>
      <div class="row">
	<div class="medium-4 columns">
	  <strong>Compte CES assignat: </strong><p>{{ projecte.compte_ces_assignat }}</p>
	</div>
	<div class="medium-4 columns">
	  <strong>Validat per: </strong><p>{{ projecte.usuaria_que_valida.username }}</p>
	</div>
      </div>
    </fieldset>
    <fieldset>
      <legend>
	Socies Afins
	<a href="{% url 'alta_socies:editar_socies_afins_projecte' projecte.id %}" class="label radius success">Afegir</a>
      </legend>
      <div class="row">
	<div class="columns">
	  <table>
	    <thead>
	      <tr>
		<th>Nom</th>
		<th>Alias</th>
		<th>1er Cognom</th>
		<th>2on Cognom</th>
		<th>Document</th>
		<th>Telefon</th>
		<th>Email</th>
	      </tr>
	    </thead>
	    <tbody>
	      {% for soci in projecte.sociaafi_set.all %}
	      <tr>
		<td>{{ soci.nom }}</td>
		<td>{{ soci.pseudonim }}</td>
		<td>{{ soci.cognom1 }}</td>
		<td>{{ soci.cognom2 }}</td>
		<td>{{ soci.dni }}</td>
		<td>{{ soci.telefon }}</td>
		<td>{{ soci.email }}</td>
	      </tr>
	      {% empty %}
	      <p> El projecte no te cap socia afí asociada. </p>
	      {% endfor %}
	    </tbody>
	  </table>
	</div>
      </div>
    </fieldset>	
  </div>
</div>
{% endblock content %}

	  
      

alta_socies/templates/alta_socies/detalls_i_validacio_projectes_pendents.html
{% extends 'layout.html' %}
{% load gci_tags %}

{% block content %}
<div class="row">
  <div class="medium-10 columns">
    <h1>{{ title }}</h1>
    <p> Cuan validis, haurás donat per entredit que el projecte ha pagat la quota d'alta i que les dades son valides </p>
  </div>
</div>
<div class="row">
  <div class="medium-12 columns">
    <fieldset>
      <legend>
	Dades del projecte
      </legend>
      <div class="row">
	<div class="medium-3 columns">
	  <strong>Nom: </strong><p>{{ projecte.nom }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Website: </strong><p>{{ projecte.website }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Email: </strong><p>{{ projecte.email }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Telefon: </strong><p>{{ projecte.telefon }}</p>
	</div>
      </div>
      <div class="row">
	<div class="medium-4 columns">
	  <strong>Descripcio: </strong><p>{{ projecte.descripcio }}</p>
	</div>
	<div class="medium-4 columns">
	  <strong>Adreça: </strong><p>{{ projecte.adreca.adreca }}</p>
	</div>
	<div class="medium-4 columns">
	  <strong>Tipus: </strong><p>{{ projecte.get_tipus_projecte_display }}</p>
	</div>
      </div>
      <div class="row">
	<div class="medium-3 medium-centered columns">
	  <strong>Forma de pagament: </strong><p>{{ projecte.get_quota_alta_forma_pagament_display }}</p>
	</div>
      </div>
    </fieldset>
  </div>
</div>
<div class="row">
  <div class="medium-12 columns">
    <fieldset>
      <legend>
	Dades mancants
      </legend>
      <div class="row">
	<div class="medium-3 columns medium-centered">
	  <form method="post">
	    {% csrf_token %}
	    {% non_field_errors form %}
	    {% form_field form.compte_ces_assignat %}
	    <button type="submit" class="radius success">Validar</button>
	  </form>
	</div>
      </div>
    </fieldset>
  </div>
</div>
{% endblock content %}

	  
      

alta_socies/templates/alta_socies/detalls_i_validacio_socies_pendents.html
{% extends 'layout.html' %}
{% load gci_tags %}

{% block content %}
<div class="row">
  <div class="medium-10 columns">
    <h1>{{ title }}</h1>
    <p> Cuan validis, haurás donat per entredit que la socia ha pagat la quota d'alta i que les dades son valides </p>
  </div>
</div>
<div class="row">
  <div class="medium-12 columns">
    <fieldset>
      <legend>
	Dades de la socia
      </legend>
      <div class="row">
	<div class="medium-3 columns">
	  <strong>Nom: </strong><p>{{ socia.socia.nom }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Primer cognom: </strong><p>{{ socia.socia.cognom1 }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Segon cognom: </strong><p>{{ socia.socia.cognom2 }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Pseudonim: </strong><p>{{ socia.socia.pseudonim }}</p>
	</div>
      </div>
      <div class="row">
	<div class="medium-3 columns">
	  <strong>Email: </strong><p>{{ socia.socia.email }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Telefon: </strong><p>{{ socia.socia.telefon }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Dni: </strong><p>{{ socia.socia.dni }}</p>
	</div>
	<div class="medium-3 columns">
	  <strong>Compte iCES: </strong><p>{{ socia.socia.compte_integralces }}</p>
	</div>
      </div>
      <div class="row">
	<div class="medium-3 medium-centered columns">
	  <strong>Forma de pagament: </strong><p>{{ socia.get_quota_alta_forma_pagament_display }}</p>
	</div>
      </div>
    </fieldset>
  </div>
</div>
<div class="row">
  <div class="medium-12 columns">
    <fieldset>
      <legend>
	Dades mancants
      </legend>
      <div class="row">
	<div class="medium-3 columns medium-centered">
	  <form method="post">
	    {% csrf_token %}
	    {% non_field_errors form %}
	    {% form_field form.compte_ces_assignat %}
	    <button type="submit" class="radius success">Validar</button>
	  </form>
	</div>
      </div>
    </fieldset>
  </div>
</div>
{% endblock content %}

	  
      

alta_socies/templates/alta_socies/editar_socia_cooperativa.html
{% extends 'layout.html' %}
{% load gci_tags %}

{% block content %}
<div class="row">
  <div class="medium-10 columns">
    <h1>{{ title }}</h1>
  </div>
</div>
<div class="row">
  <div class="medium-12 columns">
    <fieldset>
      <legend>
	Dades de la sòcia
      </legend>
      <form method="post">
	{% csrf_token %}
	{% non_field_errors form %}
	<div class="row">
	  <div class="medium-3 columns">
	    {% form_field form.nom %}
	  </div>
	  <div class="medium-3 columns">
	    {% form_field form.cognom1 %}
	  </div>
	  <div class="medium-3 columns">
	    {% form_field form.cognom2 %}
	  </div>
	  <div class="medium-3 columns">
	    {% form_field form.pseudonim %}
	  </div>
	</div>
	<div class="row">
	  <div class="medium-3 columns">
	    {% form_field form.email %}
	  </div>
	  <div class="medium-3 columns">
	    {% form_field form.telefon %}
	  </div>
	  <div class="medium-3 columns">
	    {% form_field form.dni %}
	  </div>
	</div>
	<div class="row">
	  <div class="medium-3 medium-centered columns">
	    <button type="submit" class="success radius">Desar</button>
	  </div>
	</div>
      </form>
    </fieldset>
  </div>
</div>
{% endblock content %}

	  
      

alta_socies/templates/alta_socies/filtre_habilitats.html
<div class="medium-12 columns">
  <table>
    <thead>
      <tr>
	<th>
	  COOP
	</th>
	<th>
	  Nom de la Sòcia
	</th>
      </tr>
    </thead>
    <tbody>
      {% for socia in socies %}
      <tr>
	<td>{{ socia.compte_ces_assignat }}</td>
	<td>{{ socia.socia.nom_sencer }} </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

alta_socies/templates/alta_socies/filtre_socies.html
<div class="medium-12 columns">
  <table>
    <thead>
      <tr>
	<th>
	  COOP
	</th>
	<th>
	  Nom de la Sòcia
	</th>
	<th>
	  Detalls
	</th>
      </tr>
    </thead>
    <tbody>
      {% for socia in socies %}
      <tr>
	<td>{{ socia.compte_ces_assignat }}</td>
	<td>{{ socia.socia.nom_sencer }} </td>
	<td>
	  <a href="{% url 'alta_socies:dades_socia_cooperativa' socia.id %}" class="label radius"><i class="fa fa-fw fa-check-circle-o"></i></a>
	</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

alta_socies/templates/alta_socies/formulari_projecte_collectiu_dades_generals.html
{% extends 'layout.html' %}
{% load gci_tags %}

{% block content %}
<div class="row">
  <div class="medium-10 large-10 columns">
    <h1>{{ title }}</h1>
    <h3>{{ descripcio }}</h3>
  </div>
</div>
<br />
<div class="row">
  <div class="medium-12 large-12 columns">
    <form method="post">
      {% csrf_token %}
      {% non_field_errors form %}
      <fieldset>
	<legend>
	  El teu projecte
	</legend>
	<div class="row">
	  <div class="medium-6 columns">
	    {% form_field form.nom %}
	  </div>
	  <div class="medium-6 columns">
	    {% form_field form.website %}
	  </div>
	</div>
	<div class="row">
	  <div class="medium-6 columns">
	    {% form_field form.email %}
	  </div>
	  <div class="medium-6 columns">
	    {% form_field form.telefon %}
	  </div>
	</div>
	<div class="row">
	  <div class="medium-10 columns medium-centered">
	    {% form_field form.descripcio %}
	  </div>
	</div>
      </fieldset>
      <fieldset>
	<legend>
	  Ubicació de referencia del projecte
	</legend>
	<div class="row">
	  <div class="medium-4 columns">
	    {% form_field form.pais %}
	  </div>
	  <div class="medium-4 columns">
	    {% form_field form.provincia %}
	  </div>
	  <div class="medium-4 columns">
	    {% form_field form.comarca %}
	  </div>
	</div>
	<div class="row">
	  <div class="medium-4 columns">
	    {% form_field form.poblacio %}
	  </div>
	  <div class="medium-4 columns">
	    {% form_field form.codi_postal %}
	  </div>
	  <div class="medium-4 columns">
	    {% form_field form.adreca %}
	  </div>
	</div>
      </fieldset>
      <fieldset>
	<button type="submit" class="success radius right">Segueix</button>
      </fieldset>
    </form>
  </div>
</div>
{% endblock content %}

alta_socies/templates/alta_socies/formulari_projecte_collectiu_socies_afins.html
{% extends 'layout.html' %}
{% load gci_tags %}

{% block content %}
<div class="row">
  <div class="medium-12 large-12 columns">
    <div class="panel">
      <h1>{{ title }}</h1>
      <h3>{{ descripcio }}</h3>
      <br />
      <br />
      <form method="post">
	{% csrf_token %}
	{{ formset.management_form }}
	<table>
	  <thead>
	    <tr>
	      <th>#</th>
	      <th>Nom</th>
	      <th>Cognom</th>
	      <th>Segon Cognom</th>
	      <th>Pseudonim</th>
	      <th>Email</th>
	      <th>Telefon</th>
	      <th>Tipus document</th>
	      <th>Document</th>
	    </tr>
	  </thead>
	  <tbody>
	    {% for form in formset %}
	    <tr>
	      <td>{{ forloop.counter0 }}</td>
	      <td>{% form_field form.nom %}</td>
	      <td>{% form_field form.cognom1 %}</td>
	      <td>{% form_field form.cognom2 %}</td>
	      <td>{% form_field form.pseudonim %}</td>
	      <td>{% form_field form.email %}</td>
	      <td>{% form_field form.telefon %}</td>
	      <td>{% form_field form.tipus_dni %}</td>
	      <td>{% form_field form.dni %}</td>
	      <td style="display:none;">{{ form.id }}{{ form.DELETE }}</td>
	    </tr>
	    {% endfor %}
	  </tbody>
	</table>
	<button type="submit" class="expand radius button">Validar</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

alta_socies/templates/alta_socies/formulari_sessio.html
{% extends "simple.html" %}
{% load gci_tags %}

{% block content %}
    <h1>{{ view.title }}</h1>
    <form method="post">
        {% csrf_token %}
        {% non_field_errors form %}
        <div class="row">
            <div class="medium-6 columns">
                {% form_field form.ubicacio %}
            </div>
            <div class="medium-6 columns">
                {% form_field form.responsable_alta %}
            </div>
        </div>
        <div class="row">
            <div class="medium-6 columns">
                {% form_field form.data %}
            </div>
            <div class="medium-6 columns">
                {% form_field form.duracio %}
            </div>
        </div>
        <button class="radius button" type="submit">{{ view.action_label }}</button>
    </form>
{% endblock %}

alta_socies/templates/alta_socies/formulari_socia_cooperativa_dades_alta.html
{% extends 'simple.html' %}
{% load gci_tags %}

{% block content %}
<div class="row">
  <div class="medium-10 large-10 columns large-centered medium-centered">
    <h1>{{ title }}</h1>
    <h3>{{ descripcio }}</h3>
  </div>
</div>
<div class="row">
  <div class="medium-10 columns medium-centered large-centered">
    <ul>
      <li><p><strong>En metàl·lic:</strong> Es pot realitzar el pagament a Aurea Social - Barcelona (C/ Sardenya, 263) o bé a Escudella Solidària - Girona (Psg/ Olot 68).</p></li>
      <li><p><strong>En moneda social:</strong> Per realitzar el pagament de la quota en moneda social, serà necessari que ens facis arribar el teu numero de compte amb saldo positiu, igual o superior a la quantitat a aportar, per què et puguem fer el càrrec.</p></li>
      <li><p><strong>Pagament amb hores de feina comunitària:</strong> Es pot pagar la quota aportant les teves hores al comú. Per a saber com fer-ho nomès cal que cliquis en aquest <a href="http://feina.cooperativa.cat/informacio/quota-dalta/">enllaç</a></p></li>
      <li><p><strong>Pagament a través de compte bancari:</strong>
	  <ul>
	    <li>Transferència bancària a compte de Triodos Bank: ES47 1491 0001 2910 0917 5421</li>
	    <li>Ingrés efectiu en una oficina de Cajamar (Coop. de crèdit): 3058 0523 05 2720018446</li>
	    <li>Transferència bancària a compte Caixa d'Arquitectes: ES64 3183 0800 8700 0127 8026</li>
	  </ul>
	</p>
      </li>
    </ul>
    <form method="post">
      {% csrf_token %}
      {% non_field_errors form %}
      <div class="row">
	<div class=" medium-4 columns">
	  {% form_field form.quota_alta %}
	</div>
	{{ form.te_compte_integral_ces }}
      </div>
      <div class="row">
	<div class="medium-6 columns">
	 {% form_field form.habilitats %}
	</div>
	<div class="medium-6 columns">
	  {% form_field form.contribucions %}
	</div>
      </div>
      <div class="row">
	<div class="medium-10 columns">
	  {% form_field form.detalls_habilitats %}
	</div>
      </div>
      <button type="submit" class="success radius">Validar</button>
    </form>
  </div>
</div>
{% endblock content %}